// component-factory/vue/counter-vue.vue
<template>
  <div class="s2-row">
    <wa-button size="s" appearance="outlined" @click="dec">−</wa-button>
    <strong class="s2-price">{{ count }}</strong>
    <wa-button size="s" appearance="outlined" @click="inc">+</wa-button>
    <span class="s2-quiet s2-small">vue (compiled artifact)</span>
  </div>
</template>

<script>
// Authored as a Vue SFC (options API — the factory compiles the template
// to a render function, no runtime compiler in the artifact). The atom is
// the site's shared #stores instance.
import { $counter } from "#stores";

export default {
  data: () => ({ count: $counter.get() }),
  mounted() {
    this.unsub = $counter.subscribe((value) => {
      this.count = value;
    });
  },
  unmounted() {
    this.unsub?.();
  },
  methods: {
    inc() {
      $counter.set(this.count + 1);
    },
    dec() {
      $counter.set(this.count - 1);
    },
  },
};
</script>

// component-factory/svelte/counter-svelte.svelte
<svelte:options customElement={{ tag: "s2-counter-svelte", shadow: "none" }} />

<script>
  // Authored in Svelte 5 RUNES mode (the build compiles with runes: true,
  // so legacy Svelte-4 store syntax is a compile error, not a fallback).
  // The nanostores atom binds explicitly: $state holds the local mirror,
  // $effect subscribes — its returned unsubscriber is the teardown.
  import { $counter as counter } from "#stores";

  let count = $state(counter.get());
  $effect(() => counter.subscribe((value) => { count = value; }));
</script>

<div class="s2-row">
  <wa-button size="s" appearance="outlined" onclick={() => counter.set(count - 1)}>−</wa-button>
  <strong class="s2-price">{count}</strong>
  <wa-button size="s" appearance="outlined" onclick={() => counter.set(count + 1)}>+</wa-button>
  <span class="s2-quiet s2-small">svelte (compiled artifact, runes)</span>
</div>
