// component-factory/lit/counter-lit.js
// Authored in Lit. The runtime (~16KB) is bundled into the artifact;
// state comes from the SITE's #stores atom (external in the build), so
// this counter is the same counter as every other engine's.
import { LitElement, html } from "lit";
import { $counter } from "#stores";

class S2CounterLit extends LitElement {
  static properties = { count: { state: true } };

  // Light DOM: the site cascade + wa-button styling apply directly.
  createRenderRoot() {
    return this;
  }

  connectedCallback() {
    super.connectedCallback();
    this.unsub = $counter.subscribe((value) => {
      this.count = value;
    });
  }
  disconnectedCallback() {
    super.disconnectedCallback();
    this.unsub?.();
  }
  render() {
    return html`
      <div class="s2-row">
        <wa-button size="s" appearance="outlined" @click=${() => $counter.set(this.count - 1)}>−</wa-button>
        <strong class="s2-price">${this.count}</strong>
        <wa-button size="s" appearance="outlined" @click=${() => $counter.set(this.count + 1)}>+</wa-button>
        <span class="s2-quiet s2-small">lit (compiled artifact)</span>
      </div>
    `;
  }
}

if (!customElements.get("s2-counter-lit")) customElements.define("s2-counter-lit", S2CounterLit);

// component-factory/vue/counter-vue.vue
<template>
  <div class="s2-row">
    <wa-button size="s" appearance="outlined" @click="dec">−</wa-button>
    <strong class="s2-price">{{ count }}</strong>
    <wa-button size="s" appearance="outlined" @click="inc">+</wa-button>
    <span class="s2-quiet s2-small">vue (compiled artifact)</span>
  </div>
</template>

<script>
// Authored as a Vue SFC (options API — the factory compiles the template
// to a render function, no runtime compiler in the artifact). The atom is
// the site's shared #stores instance.
import { $counter } from "#stores";

export default {
  data: () => ({ count: $counter.get() }),
  mounted() {
    this.unsub = $counter.subscribe((value) => {
      this.count = value;
    });
  },
  unmounted() {
    this.unsub?.();
  },
  methods: {
    inc() {
      $counter.set(this.count + 1);
    },
    dec() {
      $counter.set(this.count - 1);
    },
  },
};
</script>
